### ISSUE TITLE
Specify overlap length

### ISSUE THREAD

**Issue by bfebles** [jbloomlab/phipseq_oligodesign#1]
How to find an option for overlap length? There seems to be no option for that.

**Comment by jbloom** [comment]
@khdusenbury, are you able to reply to this one?

**Comment by khdcrawford** [comment]
Yes, I can take a look tonight.

**Comment by khdcrawford** [comment]
Hi @bfebles, 

Instead of specifying overlap length, we specify how much the oligos should "tile" by. This is specified with the `--tile` argument. 

For the defaults, oligo length is 117 and the tile is 60, so each oligo advances by 60 nts and adjacent oligos have an overlap of 57 nts. If you want to make the overlap shorter, you can increase `tile` or to make the oligos overlap more, you can decrease `tile`. 

Hopefully that makes sense. I'm going to go ahead and close the issue, but feel free to re-open it or raise another one if you continue to have questions or issues with the code!
